name: Build
on:
  push:
    branches:
      - main
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request:
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@62580a2290da7a11a4332bbafc49ecb895d6873e # v3.0.0
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@62580a2290da7a11a4332bbafc49ecb895d6873e # v3.0.0
  build:
    uses: vidavidorra/.github/.github/workflows/node-build.yml@62580a2290da7a11a4332bbafc49ecb895d6873e # v3.0.0
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Setup node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
      - name: Test
        uses: renovatebot/github-action@8dd353442b603b79e9ad46ebd25bdac25d67ccfa # v38.1.13
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: full
          RENOVATE_REPOSITORIES: '["vidavidorra/renovate"]'
  release:
    needs: [lint-commit-messages, lint, build, test]
    uses: vidavidorra/.github/.github/workflows/release.yml@62580a2290da7a11a4332bbafc49ecb895d6873e # v3.0.0
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
