name: Build
on:
  push:
    branches:
      - main
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 14
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Lint
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 14
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      CONFIG_FILE_PATH: dist/test/config.json
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 14
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Prepare test
        run: |
          npm run build
          npm run test:create-renovate-config -- ${{ env.CONFIG_FILE_PATH }}
      - name: Test
        uses: renovatebot/github-action@19fcb7282281b0f02488bb772042f53ba654a99e # v34.141.0
        with:
          configurationFile: ${{ env.CONFIG_FILE_PATH }}
          token: ${{ secrets.RENOVATE_TOKEN }}
  release:
    needs: [lint, build, test]
    runs-on: ubuntu-latest
    # GitHub API requests can easy take a couple of seconds and the release can
    # make lots of API requests when a release has a lot of commits. If every
    # requests takes five seconds, which is on the high side for a request, this
    # could perform 180 requests. This should be enough for most use cases.
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          # Make sure the release step uses its own credentials.
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 14
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: vidavidorra-release
          GIT_AUTHOR_EMAIL: 65564857+vidavidorra-release@users.noreply.github.com
          GIT_COMMITTER_NAME: vidavidorra-release
          GIT_COMMITTER_EMAIL: 65564857+vidavidorra-release@users.noreply.github.com
        run: npx --no-install semantic-release
