name: Build
on:
  push:
    branches:
      - main
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - name: Setup node
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: 14
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Lint
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - name: Setup node
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: 14
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      CONFIG_FILE_PATH: dist/test/config.json
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - name: Setup node
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: 14
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Prepare test
        run: |
          npm run build
          npm run test:create-renovate-config -- ${{ env.CONFIG_FILE_PATH }}
      - name: Test
        uses: renovatebot/github-action@6030949931ad2285e5e0fbe5101c2052c540262c # tag=v26.21.7
        with:
          configurationFile: ${{ env.CONFIG_FILE_PATH }}
          token: ${{ secrets.RENOVATE_TOKEN }}
  release:
    needs: [lint, build, test]
    runs-on: ubuntu-latest
    # GitHub API requests can easy take a couple of seconds and the release can
    # make lots of API requests when a release has a lot of commits. If every
    # requests takes five seconds, which is on the high side for a request, this
    # could perform 180 requests. This should be enough for most use cases.
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          # Make sure the release step uses its own credentials.
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: 14
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: vidavidorra-release
          GIT_AUTHOR_EMAIL: 65564857+vidavidorra-release@users.noreply.github.com
          GIT_COMMITTER_NAME: vidavidorra-release
          GIT_COMMITTER_EMAIL: 65564857+vidavidorra-release@users.noreply.github.com
        run: npx --no-install semantic-release
