name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request: null
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@caca0142cfe8f96afe334a064832bbe763a4788e # v4.2.41
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@caca0142cfe8f96afe334a064832bbe763a4788e # v4.2.41
  build:
    uses: vidavidorra/.github/.github/workflows/node-build.yml@caca0142cfe8f96afe334a064832bbe763a4788e # v4.2.41
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Setup node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      - name: Test
        uses: renovatebot/github-action@b9486682a19fe4ea2dd1263c11b4e0c1fe1838fe # v40.3.2
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: full
          RENOVATE_REPOSITORIES: '["vidavidorra/renovate"]'
  release:
    needs:
      - lint-commit-messages
      - lint
      - build
      - test
    uses: vidavidorra/.github/.github/workflows/release.yml@caca0142cfe8f96afe334a064832bbe763a4788e # v4.2.41
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
