name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request: null
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@353e69314e05e5b4117892956a566a70142721fc # v4.2.42
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@353e69314e05e5b4117892956a566a70142721fc # v4.2.42
  build:
    uses: vidavidorra/.github/.github/workflows/node-build.yml@353e69314e05e5b4117892956a566a70142721fc # v4.2.42
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      - name: Test
        uses: renovatebot/github-action@80eaf969abf68ad62aa94d9ab392421b31621634 # v40.3.4
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: full
          RENOVATE_REPOSITORIES: '["vidavidorra/renovate"]'
  release:
    needs:
      - lint-commit-messages
      - lint
      - build
      - test
    uses: vidavidorra/.github/.github/workflows/release.yml@353e69314e05e5b4117892956a566a70142721fc # v4.2.42
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
