name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request: null
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@86214907bfc65c10478602c68a16c7e4c60398da # v5.0.17
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@86214907bfc65c10478602c68a16c7e4c60398da # v5.0.17
  build:
    uses: vidavidorra/.github/.github/workflows/node-build.yml@86214907bfc65c10478602c68a16c7e4c60398da # v5.0.17
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      - name: Test
        uses: renovatebot/github-action@531c6786d6cf05ef148c4cfe251745c2c6de442c # v41.0.9
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: full
          RENOVATE_REPOSITORIES: '["vidavidorra/renovate"]'
  release:
    needs:
      - lint-commit-messages
      - lint
      - build
      - test
    uses: vidavidorra/.github/.github/workflows/release.yml@86214907bfc65c10478602c68a16c7e4c60398da # v5.0.17
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
