name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request: null
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@a733c9c5f0741127e1f07c53e3d616271dca0157 # v4.2.4
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@a733c9c5f0741127e1f07c53e3d616271dca0157 # v4.2.4
  build:
    uses: vidavidorra/.github/.github/workflows/node-build.yml@a733c9c5f0741127e1f07c53e3d616271dca0157 # v4.2.4
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      - name: Test
        uses: renovatebot/github-action@89bd050bafa5a15de5d9383e3129edf210422004 # v40.1.5
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: full
          RENOVATE_REPOSITORIES: '["vidavidorra/renovate"]'
  release:
    needs:
      - lint-commit-messages
      - lint
      - build
      - test
    uses: vidavidorra/.github/.github/workflows/release.yml@a733c9c5f0741127e1f07c53e3d616271dca0157 # v4.2.4
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
