name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request: null
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@f9dd5c7e1a71d02a92f8aac3261b62eae0df950f # v4.1.0
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@f9dd5c7e1a71d02a92f8aac3261b62eae0df950f # v4.1.0
  build:
    uses: vidavidorra/.github/.github/workflows/node-build.yml@f9dd5c7e1a71d02a92f8aac3261b62eae0df950f # v4.1.0
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup node
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
      - name: Test
        uses: renovatebot/github-action@5c6c06aa0e3d7a6a9b6cba05c078c51631b5f11a # v39.1.1
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: full
          RENOVATE_REPOSITORIES: '["vidavidorra/renovate"]'
  release:
    needs: [lint-commit-messages, lint, build, test]
    uses: vidavidorra/.github/.github/workflows/release.yml@f9dd5c7e1a71d02a92f8aac3261b62eae0df950f # v4.1.0
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
