name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request: null
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@8bca8c5a41cf3a33b637ea20f6b5aee8c3fcc9cc # v4.2.40
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@8bca8c5a41cf3a33b637ea20f6b5aee8c3fcc9cc # v4.2.40
  build:
    uses: vidavidorra/.github/.github/workflows/node-build.yml@8bca8c5a41cf3a33b637ea20f6b5aee8c3fcc9cc # v4.2.40
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Setup node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      - name: Test
        uses: renovatebot/github-action@a1ed1d0adddfdf138192d1fbe3150a80094dee6a # v40.3.1
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: full
          RENOVATE_REPOSITORIES: '["vidavidorra/renovate"]'
  release:
    needs:
      - lint-commit-messages
      - lint
      - build
      - test
    uses: vidavidorra/.github/.github/workflows/release.yml@8bca8c5a41cf3a33b637ea20f6b5aee8c3fcc9cc # v4.2.40
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
