name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request: null
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@da403f76f1ebe37871e4374d673eb78c9d64f19d # v4.2.38
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@da403f76f1ebe37871e4374d673eb78c9d64f19d # v4.2.38
  build:
    uses: vidavidorra/.github/.github/workflows/node-build.yml@da403f76f1ebe37871e4374d673eb78c9d64f19d # v4.2.38
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      - name: Test
        uses: renovatebot/github-action@dd4d265eb8646cd04fc5f86ff8bc8d496d75a251 # v40.2.8
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: full
          RENOVATE_REPOSITORIES: '["vidavidorra/renovate"]'
  release:
    needs:
      - lint-commit-messages
      - lint
      - build
      - test
    uses: vidavidorra/.github/.github/workflows/release.yml@da403f76f1ebe37871e4374d673eb78c9d64f19d # v4.2.38
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
