name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request: null
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@c837c2a0a83e59cb2e7b270e2e493e74e5c2d274 # v5.0.8
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@c837c2a0a83e59cb2e7b270e2e493e74e5c2d274 # v5.0.8
  build:
    uses: vidavidorra/.github/.github/workflows/node-build.yml@c837c2a0a83e59cb2e7b270e2e493e74e5c2d274 # v5.0.8
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      - name: Test
        uses: renovatebot/github-action@936628dfbff213ab2eb95033c5e123cfcaf09ebb # v41.0.5
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: full
          RENOVATE_REPOSITORIES: '["vidavidorra/renovate"]'
  release:
    needs:
      - lint-commit-messages
      - lint
      - build
      - test
    uses: vidavidorra/.github/.github/workflows/release.yml@c837c2a0a83e59cb2e7b270e2e493e74e5c2d274 # v5.0.8
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
