name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request: null
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@cccc592e98e8d7089d7267f3505374f447be71d1 # v4.2.31
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@cccc592e98e8d7089d7267f3505374f447be71d1 # v4.2.31
  build:
    uses: vidavidorra/.github/.github/workflows/node-build.yml@cccc592e98e8d7089d7267f3505374f447be71d1 # v4.2.31
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      - name: Test
        uses: renovatebot/github-action@259200be4d976a76196ec8985b0dddcaf1733b47 # v40.2.0
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: full
          RENOVATE_REPOSITORIES: '["vidavidorra/renovate"]'
  release:
    needs:
      - lint-commit-messages
      - lint
      - build
      - test
    uses: vidavidorra/.github/.github/workflows/release.yml@cccc592e98e8d7089d7267f3505374f447be71d1 # v4.2.31
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
