name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request: null
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@0d26596b8ec32cde40a2c8f96e73d4073e6a7be2 # v4.1.6
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@0d26596b8ec32cde40a2c8f96e73d4073e6a7be2 # v4.1.6
  build:
    uses: vidavidorra/.github/.github/workflows/node-build.yml@0d26596b8ec32cde40a2c8f96e73d4073e6a7be2 # v4.1.6
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      - name: Test
        uses: renovatebot/github-action@42c1d3cb1d1ca891765626ba71cdff5e757258de # v40.0.2
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: full
          RENOVATE_REPOSITORIES: '["vidavidorra/renovate"]'
  release:
    needs: [lint-commit-messages, lint, build, test]
    uses: vidavidorra/.github/.github/workflows/release.yml@0d26596b8ec32cde40a2c8f96e73d4073e6a7be2 # v4.1.6
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
