name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request: null
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@e84314ffa98a80fb404e08fb6accf04508ba743e # v5.0.6
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@e84314ffa98a80fb404e08fb6accf04508ba743e # v5.0.6
  build:
    uses: vidavidorra/.github/.github/workflows/node-build.yml@e84314ffa98a80fb404e08fb6accf04508ba743e # v5.0.6
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      - name: Test
        uses: renovatebot/github-action@0984fb80fc633b17e57f3e8b6c007fe0dc3e0d62 # v40.3.6
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: full
          RENOVATE_REPOSITORIES: '["vidavidorra/renovate"]'
  release:
    needs:
      - lint-commit-messages
      - lint
      - build
      - test
    uses: vidavidorra/.github/.github/workflows/release.yml@e84314ffa98a80fb404e08fb6accf04508ba743e # v5.0.6
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
