name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request: null
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@4518aa120d8e5f094249c7445a5dca864378c042 # v4.2.37
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@4518aa120d8e5f094249c7445a5dca864378c042 # v4.2.37
  build:
    uses: vidavidorra/.github/.github/workflows/node-build.yml@4518aa120d8e5f094249c7445a5dca864378c042 # v4.2.37
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      - name: Test
        uses: renovatebot/github-action@dd4d265eb8646cd04fc5f86ff8bc8d496d75a251 # v40.2.8
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: full
          RENOVATE_REPOSITORIES: '["vidavidorra/renovate"]'
  release:
    needs:
      - lint-commit-messages
      - lint
      - build
      - test
    uses: vidavidorra/.github/.github/workflows/release.yml@4518aa120d8e5f094249c7445a5dca864378c042 # v4.2.37
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
