name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request: null
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@3a415d7438e0ffab3441b52eef7b7226afcb88e2 # v4.2.34
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@3a415d7438e0ffab3441b52eef7b7226afcb88e2 # v4.2.34
  build:
    uses: vidavidorra/.github/.github/workflows/node-build.yml@3a415d7438e0ffab3441b52eef7b7226afcb88e2 # v4.2.34
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      - name: Test
        uses: renovatebot/github-action@630a255a1f2f56c8d8ce160bed3e3ca577ca53e2 # v40.2.7
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: full
          RENOVATE_REPOSITORIES: '["vidavidorra/renovate"]'
  release:
    needs:
      - lint-commit-messages
      - lint
      - build
      - test
    uses: vidavidorra/.github/.github/workflows/release.yml@3a415d7438e0ffab3441b52eef7b7226afcb88e2 # v4.2.34
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
