name: Renovate
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/30 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
      - name: Setup node
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # tag=v3.1.0
        with:
          node-version: 14
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
      - name: Renovate
        uses: renovatebot/github-action@6030949931ad2285e5e0fbe5101c2052c540262c # tag=v26.21.7
        with:
          configurationFile: dist/src/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
